[package]
name = "easypdf-desktop"
description = "EasyPDF desktop shell."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde.workspace = true
easypdf-core.workspace = true
easypdf-render.workspace = true
easypdf-ffi.workspace = true
tauri-plugin-dialog = "2.7.2"

[lints]
workspace = true
