[package]
name = "easypdf-ffi"
description = "Protocol for the sandboxed parse and render worker process."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
easypdf-core = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
serde_json = "1"
